SYSTEM=gp2x
# SYSTEM=linux

VERSION=1.3

# DEBUG=-g

ifeq ($(SYSTEM),gp2x)
	CPP=arm-gp2x-linux-c++
	INCBASE=/gp2xsdk/Tools/arm-gp2x-linux/include
	LIBBASE=/gp2xsdk/Tools/arm-gp2x-linux/lib
	DEFINE=GP2X
	TARGET=$(TARGETGP2X)
else
	CPP=g++
	INCBASE=/usr/include
	LIBBASE=/usr/lib
	DEFINE=LINUX
	TARGET=$(TARGETLINUX)
endif

CFLAGS=-Wall -D$(DEFINE) -I$(INCBASE) -I$(INCBASE)/SDL
LDFLAGS=-L$(LIBBASE) -lz -lfreetype -lpng -ljpeg -lSDL_ttf -lSDL_image -lSDL
